#!/usr/bin/env bash
# =============================================================================
# scripts/lib/apply-common.sh — shared apply-layer primitives (ralplan T10)
# -----------------------------------------------------------------------------
# SOURCED by apply-noesis-profiles.sh and apply-agency-profiles.sh.
# Never executed directly. Sourcing guard at top.
#
# Conventions:
#   AC_DRY=1            dry-run mode: ac_run prints "[dry-run]" instead of exec
#   AC_PROFILE_CMD      hermes binary override (default: hermes / $HERMES_BIN)
#   AC_NO_TUNE=1        skip model-lane verification/tuning
# =============================================================================
[[ "${_APPLY_COMMON_SOURCED:-}" == "1" ]] && return 0
_APPLY_COMMON_SOURCED=1

: "${AC_DRY:=0}"
: "${AC_NO_TUNE:=0}"
AC_PROFILE_CMD="${HERMES_BIN:-hermes}"

ac_log()  { printf '%s\n' "$*"; }
ac_warn() { printf 'WARNING: %s\n' "$*" >&2; }

# dry-run aware command runner
ac_run() {
  if [[ "$AC_DRY" -eq 1 ]]; then
    ac_log "  [dry-run] $*"
  else
    "$@"
  fi
}

# resolve bundle: prefer canonical repo, fall back to dir sibling to script
ac_resolve_bundle() {
  local preferred="$1" self_dir="$2"
  if [[ -d "$preferred/agents" ]]; then
    printf '%s\n' "$preferred"; return 0
  fi
  if [[ -d "$self_dir/agents" ]]; then
    printf '%s\n' "$self_dir"; return 0
  fi
  return 1
}

# noesis roster rows from profiles/noesis-roster.yaml:
#   name|profile|wave|model|provider|cwd
ac_roster_rows_noesis() {
  python3 - "$1" <<'PYEOF'
import sys, yaml
data = yaml.safe_load(open(sys.argv[1]))
for name, p in (data.get("profiles") or {}).items():
    am = p.get("apply_model") or {}
    profile = p.get("maps_to") or name
    print("|".join([
        name,
        str(profile),
        str(p.get("wave", "")),
        str(am.get("model", "")),
        str(am.get("provider", "")),
        str(p.get("terminal_cwd", "")),
    ]))
PYEOF
}

# agency roster rows from .scratch/roster.yaml (generated by convert.py):
#   name|profile|wave|model|provider|cwd
ac_roster_rows_agency() {
  python3 - "$1" <<'PYEOF'
import sys, yaml
data = yaml.safe_load(open(sys.argv[1]))
for p in (data.get("profiles") or []):
    print("|".join([
        str(p.get("name")),
        str(p.get("name")),
        str(p.get("wave", "")),
        str(p.get("model", "")),
        str(p.get("provider", "")),
        ".",
    ]))
PYEOF
}

# verify a model/provider lane with a real one-shot call (offline-safe: the
# caller must gate this behind AC_NO_TUNE / dry-run policy)
ac_verify_lane() {
  local model="$1" provider="$2" name="$3"
  local out
  out=$(timeout 90 "$AC_PROFILE_CMD" -p "$name" chat -q "Reply with exactly: LANE_OK" -Q \
        -m "$model" --provider "$provider" 2>&1 || true)
  [[ "$out" == *LANE_OK* ]]
}

# structured audit record (JSONL) — open-questions ruling: roster hash, pin,
# installed list, plugin hash, rollback target.
# usage: ac_audit <home> <script> <mode> <status> <roster_sha> <plugin_sha> <rollback> <profiles...>
ac_audit() {
  local home="$1" script="$2" mode="$3" status="$4"
  local roster_sha="$5" plugin_sha="$6" rollback="$7"
  shift 7
  local profiles_json
  profiles_json=$(printf '%s\n' "$@" | python3 -c 'import sys,json; print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))')
  local ts
  ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  mkdir -p "$home/logs"
  printf '{"ts":%s,"script":%s,"home":%s,"mode":%s,"status":%s,"roster_sha256":%s,"plugin_sha256":%s,"rollback":%s,"profiles":%s}\n' \
    "$(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$ts")" \
    "$(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$script")" \
    "$(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$home")" \
    "$(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$mode")" \
    "$(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$status")" \
    "$(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$roster_sha")" \
    "$(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$plugin_sha")" \
    "$(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$rollback")" \
    "$profiles_json" >> "$home/logs/apply-audit.jsonl"
}

# snapshot an existing profile dir for rollback; echoes backup root (once)
ac_backup_profile() {
  local home="$1" profile="$2" backup_root="$3"
  local target="$home/profiles/$profile"
  [[ -d "$target" ]] || return 0
  if [[ "$AC_DRY" -eq 1 ]]; then
    ac_log "  [dry-run] backup $profile -> $backup_root/$profile"
    return 0
  fi
  mkdir -p "$backup_root/$profile"
  cp -a "$target/." "$backup_root/$profile/" 2>/dev/null || true
}
