#!/usr/bin/env bash
# =============================================================================
# apply-agency-profiles.sh — ralplan T12: apply the 18-agent Tier A agency
# catalog as Hermes bot profiles. Roster-driven; mirrors apply-noesis-profiles.
# Specs are generated by agency/convert.py into the gitignored agency/.scratch/
# tree (2-tier architecture); this script only READS generated artifacts.
#
# Safety properties (ralplan §3 + §7):
#   * Canary precondition (N0): .scratch/ must already be built AND green
#     under agency/validate-specs.py. Refuses to run otherwise — never
#     regenerates specs implicitly.
#   * Runtime secret assertion (N5, layer 3): agency/secretscan.py runs over
#     the generated tree up front and over every artifact before install.
#   * Model lanes verified with a one-shot smoke call before tuning.
#   * Audit record (JSONL) + rollback snapshot dir per run.
#   * Wave deployment is gated: this script is the mechanism, not the
#     authorization. Waves are frozen (8 + 10) in agency/curation.yaml.
#
# Usage:
#   ./apply-agency-profiles.sh [--home DIR] [--list] [--all] [--wave N]
#                              [--only name ...] [--dry-run]
#                              [--no-model-tuning] [--yes]
# =============================================================================
set -euo pipefail
umask 077

SELF_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
# shellcheck source=lib/apply-common.sh
source "$SELF_DIR/lib/apply-common.sh"

# ---- defaults ---------------------------------------------------------------
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
DRY=0; TUNE_MODELS=1; ASSUME_YES=0; CHECK=0
DO_LIST=0; DO_ALL=0; WAVE=""; WANT=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --home) HERMES_HOME="$2"; shift 2 ;;
    --list) DO_LIST=1; shift ;;
    --all) DO_ALL=1; shift ;;
    --check) CHECK=1; shift ;;
    --wave) WAVE="$2"; shift 2 ;;
    --only) shift; while [[ $# -gt 0 && "$1" != --* ]]; do WANT+=("$1"); shift; done ;;
    --dry-run) DRY=1; shift ;;
    --no-model-tuning) TUNE_MODELS=0; shift ;;
    --yes) ASSUME_YES=1; shift ;;
    -h|--help) grep '^#' "$0" | head -30; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

AC_DRY="$DRY"
[[ $TUNE_MODELS -eq 1 ]] || AC_NO_TUNE=1
export HERMES_HOME

# ---- repo / artifact resolution ---------------------------------------------
REPO_ROOT="$(cd "$(dirname "$SELF_DIR")" && pwd)"
AGENCY_DIR="$REPO_ROOT/agency"
SCRATCH="$AGENCY_DIR/.scratch"
SECRETSCAN="$AGENCY_DIR/secretscan.py"
VALIDATOR="$AGENCY_DIR/validate-specs.py"
CURATION="$AGENCY_DIR/curation.yaml"
ROSTER_YAML="$SCRATCH/roster.yaml"
PLUGIN_JSON="$AGENCY_DIR/integrations/hermes-plugin/agency-agents-router/data/agents.json"

# ---- precondition (N0 canary): scratch tree must be built --------------------
if [[ ! -d "$SCRATCH/agents" || ! -f "$ROSTER_YAML" ]]; then
  echo "ERROR: $SCRATCH tree not found (or roster.yaml missing)." >&2
  echo "Build first:  python3 agency/convert.py --full-tree" >&2
  exit 1
fi

# ---- precondition: validator green (staleness + secrets + L3 guard) ----------
if [[ $DRY -eq 1 ]]; then
  ac_log "dry-run: skipping validator (run for real: python3 $VALIDATOR)"
else
  ac_log "Precondition: agency/validate-specs.py ..."
  python3 "$VALIDATOR" || {
    echo "ERROR: validator failed — refusing to apply (canary precondition)." >&2
    exit 1; }
fi

# ---- runtime secret assertion (N5 layer 3): whole tree up front --------------
if ! python3 "$SECRETSCAN" "$SCRATCH" >/dev/null 2>&1; then
  echo "ERROR: secret-scan HIT in $SCRATCH — aborting (N5)." >&2
  exit 1
fi
assert_no_secrets() { # $1 = file; abort the apply on any hit
  if ! python3 "$SECRETSCAN" "$1" >/dev/null 2>&1; then
    echo "ERROR: secret-scan HIT in $1 — aborting apply (N5)." >&2
    exit 1
  fi
}

# ---- roster rows (name|name|wave|model|provider|cwd); wave from roster ------
mapfile -t ROSTER < <(ac_roster_rows_agency "$ROSTER_YAML")
[[ ${#ROSTER[@]} -gt 0 ]] || { echo "ERROR: no profiles in $ROSTER_YAML" >&2; exit 1; }

if [[ $CHECK -eq 1 ]]; then
  ac_log "check OK: scratch tree present, validator green, secret scan clean, ${#ROSTER[@]} profiles in roster"
  exit 0
fi

# wave membership straight from the roster rows (field 3)
declare -A WAVE_OF=()
for row in "${ROSTER[@]}"; do
  IFS='|' read -r rn _ rw _ _ _ <<< "$row"
  WAVE_OF["$rn"]="$rw"
done

# ---- selector ------------------------------------------------------------------
selected() { # $1 = profile name
  local n="$1" w
  if [[ ${#WANT[@]} -gt 0 ]]; then
    for w in "${WANT[@]}"; do
      [[ "$n" == "$w" || "$n" == "agency-$w" ]] && return 0
    done
    return 1
  fi
  [[ $DO_ALL -eq 1 ]] && return 0
  [[ -n "$WAVE" && "${WAVE_OF[$n]:-}" == "$WAVE" ]] && return 0
  return 1
}

if [[ $DO_LIST -eq 1 || ( $DO_ALL -eq 0 && ${#WANT[@]} -eq 0 && -z "$WAVE" ) ]]; then
  ac_log "Agency roster (${#ROSTER[@]} profiles, waves from curation.yaml):"
  for row in "${ROSTER[@]}"; do
    n="${row%%|*}"
    printf '  %-42s wave=%s\n' "$n" "${WAVE_OF[$n]:-?}"
  done
  ac_log ""
  ac_log "Select with --all, --wave N, or --only <name> ..."
  exit 0
fi

# ---- plan ----------------------------------------------------------------------
ac_log "Agency profile apply (ralplan T12)"
ac_log "  Hermes home : $HERMES_HOME"
ac_log "  Scratch     : $SCRATCH (gitignored, generated)"
ac_log "  Mode        : $([[ $DRY -eq 1 ]] && echo DRY-RUN || echo APPLY)"
ac_log "  Model tuning: $([ $TUNE_MODELS -eq 1 ] && echo ON || echo OFF)"
ac_log ""
ac_log "Planned changes:"
APPLY=()
for row in "${ROSTER[@]}"; do
  n="${row%%|*}"
  if selected "$n"; then
    action="create"; [[ -d "$HERMES_HOME/profiles/$n" ]] && action="refresh"
    printf '  %-42s %s (wave %s)\n' "$n" "$action" "${WAVE_OF[$n]:-?}"
    APPLY+=("$n")
  fi
done
ac_log ""
[[ ${#APPLY[@]} -eq 0 ]] && { ac_log "Nothing selected — exiting."; exit 0; }
[[ $DRY -eq 1 ]] && ac_log "DRY-RUN — no changes will be made."
if [[ $DRY -eq 0 && $ASSUME_YES -ne 1 ]]; then
  read -r -p "Proceed with ${#APPLY[@]} agency profile(s)? [y/N] " reply
  [[ "$reply" == "y" || "$reply" == "Y" ]] || { ac_log "Aborted."; exit 0; }
fi
ac_log ""

# ---- apply ----------------------------------------------------------------------
created=0; refreshed=0; skipped=0; failed=()
TS="$(date +%Y%m%d-%H%M%S)"
BACKUP_ROOT="$HERMES_HOME/.profile-backups/agency-$TS"

[[ -x "$(command -v "$AC_PROFILE_CMD")" ]] || { ac_warn "$AC_PROFILE_CMD not on PATH"; AC_PROFILE_CMD=hermes; }

for name in "${APPLY[@]}"; do
  row=""
  for r in "${ROSTER[@]}"; do [[ "${r%%|*}" == "$name" ]] && row="$r" && break; done
  [[ -n "$row" ]] || { ac_warn "unknown profile '$name'; skipping"; continue; }
  IFS='|' read -r _ _ _ model provider cwd <<< "$row"
  [[ -n "$cwd" ]] || cwd="."

  target="$HERMES_HOME/profiles/$name"
  ac_backup_profile "$HERMES_HOME" "$name" "$BACKUP_ROOT"

  src_soul="$SCRATCH/agents/$name/SOUL.md"
  src_yaml="$SCRATCH/agents/$name/agent.yaml"
  if [[ ! -f "$src_soul" ]]; then
    ac_warn "missing $src_soul — skipping"; failed+=("$name"); continue
  fi
  assert_no_secrets "$src_soul"
  assert_no_secrets "$src_yaml"

  # description from generated agent.yaml (used at create time)
  spec_desc="$(python3 - "$src_yaml" <<'PYEOF'
import sys, yaml
d = yaml.safe_load(open(sys.argv[1], encoding="utf-8")) or {}
hp = (d.get("agent") or {}).get("hermes_profile") or {}
print(" ".join(str(hp.get("description") or d.get("description") or "").split()))
PYEOF
)"

  if [[ ! -d "$target" ]]; then
    ac_log "  + creating $name"
    ac_run "$AC_PROFILE_CMD" profile create "$name" --no-alias \
           --description "$spec_desc" >/dev/null 2>&1 || {
      ac_warn "create failed for $name"; failed+=("$name"); continue; }
    if [[ -f "$HERMES_HOME/config.yaml" ]]; then
      ac_run cp "$HERMES_HOME/config.yaml" "$target/config.yaml" 2>/dev/null || true
      ac_run cp "$HERMES_HOME/.env" "$target/.env" 2>/dev/null || true
    fi
    created=$((created+1))
  else
    if [[ -f "$target/SOUL.md" ]] && cmp -s "$src_soul" "$target/SOUL.md"; then
      skipped=$((skipped+1))
      ac_log "  = exists   $name; SOUL current (skip)"
    else
      refreshed=$((refreshed+1))
      ac_log "  = exists   $name; refreshing SOUL"
    fi
  fi

  if [[ ! -f "$target/SOUL.md" ]] || ! cmp -s "$src_soul" "$target/SOUL.md"; then
    ac_run cp "$src_soul" "$target/SOUL.md"
  fi

  # terminal.cwd
  ac_run "$AC_PROFILE_CMD" -p "$name" config set terminal.cwd "$cwd" >/dev/null 2>&1 || true

  # model routing (verified lane, per curation apply_model via roster.yaml)
  if [[ $TUNE_MODELS -eq 1 && -n "$model" ]]; then
    if ac_verify_lane "$model" "$provider" "$name"; then
      ac_log "      model $model @ $provider [verified]"
      ac_run "$AC_PROFILE_CMD" -p "$name" config set model.default "$model" >/dev/null 2>&1
      ac_run "$AC_PROFILE_CMD" -p "$name" config set model.provider "$provider" >/dev/null 2>&1
    else
      ac_warn "lane $model@$provider failed verification; keeping current model for $name"
    fi
  fi
done

# ---- audit record (N7) ------------------------------------------------------------
if [[ $DRY -eq 0 ]]; then
  roster_sha="$(sha256sum "$CURATION" | cut -d' ' -f1)"
  plugin_sha="-"
  [[ -f "$PLUGIN_JSON" ]] && plugin_sha="$(sha256sum "$PLUGIN_JSON" | cut -d' ' -f1)"
  status="ok"; [[ ${#failed[@]} -gt 0 ]] && status="partial"
  ac_audit "$HERMES_HOME" "apply-agency-profiles.sh" "apply" "$status" \
           "$roster_sha" "$plugin_sha" "$BACKUP_ROOT" "${APPLY[@]}"
fi

ac_log ""
ac_log "Done: created=$created refreshed=$refreshed skipped=$skipped failed=${#failed[@]}"
[[ ${#failed[@]} -gt 0 ]] && { ac_log "Failed: ${failed[*]}"; exit 1; }
exit 0
